Improve error messaging when shellcheck enounters unexpected yaml
If eval of the selector fails, display a nice error message

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -63,7 +63,14 @@ shellcheck:
         while [ "$documentIndex" -lt "$documentCount" ]; do
           true $((documentIndex=documentIndex+1))
           yq eval 'select(documentIndex == '${documentIndex}') | .[] | select(tag=="!!map") | (.before_script,.script,.after_script) | select(. != null ) | path | "select(documentIndex == '${documentIndex}') | .[\"" + join("\"].[\"") + "\"]"' "${file}" | while IFS= read -r selector; do
+            set -e
             script=$(yq eval "${selector} | join(\"${newline}\")" "${file}")
+            status=$?
+            set +e
+            if [ $status -ne 0 ]; then
+              >&2 printf "\nError getting the contents of the selector %s in the file %s:\n\nThe YAML may be malformed." "${selector}" "${file}"
+              exit 1
+            fi
             if ! printf '%s' "${script}" | shellcheck -x -; then
               >&2 printf "\nError in %s in the script specified in %s:\n%s\n" "${file}" "${selector}" "${script}"
               exit 1
